### ISSUE TITLE
Software - MySQL

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Installation-Guides#17]
child of #1

**Comment by chrismclarke** [comment]
recommendations:

1. Probably a site-wide change, but add spacing below bullets
2. Make stronger emphasis on the 'Do not forget this password' - this will probably want it's own box to stress the importance that they keep it safe (maybe write down somewhere)
3. Like the good practice recommendation, again we can perhaps style this and make consistent throughout
4. Add a screenshot to show add user screen to help emphasise the importance of doing this and remove confusion from all optional settings (default is fine I assume, screenshot included)
5. How important is the user logging? It adds a couple layers of complexity, which if never used adds excess to the guide. Are the default options really that bad? (genuine question, I have no idea myself)

![mysql-new-user.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d112069d5d2d20003340bb/125516c66e82c728ace21e0d46e58d89328ecea78afef256b758e2d665043761260ea62864c7b96aea407e570e5c46fa425f5645fcaa892ba0e56d738f5f08e4c3714d36976345f3e5db55ea43a82a994e8dbcbd8f48c2eb3a22e48f8b4f3d1e1755.png)

**Comment by chrismclarke** [comment]
also just to check, by default is mysql for excel installed? No biggie to send for standalone installer if not, I just can't remember what the default behaviour was during the workshop

**Comment by dave-mills** [comment]
MySQL for Excel is installed by default if you choose developer defaults. 

Logging is important (I think - even if you never use it, it's good to have in case of emergency), but your comment prompted me to look into it and realise that binary logging is enabled by default, so we can skip those steps entirely!
