### ISSUE TITLE
Software - DB Forge

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Installation-Guides#7]
child of #1

**Comment by dave-mills** [comment]
Interestingly, this appears to have quite a nice CSV / data import function. It's more steps than Heidi, but it has more features and I think they're actually better described. For e.g. it lets you: 

 - use a csv file to create a new table, with a screen to check and manually specify the data types;
 - insert into an existing table and manually map columns in your csv file to columns in your table. (In case your csv columns are in a different order, or if you're only importing a subset of the columns). 

(It lets you import from Excel too, but the free version is limited to 50 rows.)

I don't think it's worth changing any of our default advice on what to use, but I'll definitely highlight this as a nice feature in the doc.
